global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "auth-service"
    static_configs:
      - targets: ["auth-service:5000"]

  - job_name: "product-service"
    static_configs:
      - targets: ["product-service:5001"]

  - job_name: "order-service"
    static_configs:
      - targets: ["order-service:5002"]

  - job_name: "rabbitmq"
    static_configs:
      - targets: ["rabbitmq:15692"]