name: CI - Auth Service

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'backend/auth-service/**'
      - '.github/workflows/ci-auth-service.yml'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'backend/auth-service/**'
      - '.github/workflows/ci-auth-service.yml'

jobs:
  test-auth-service:
    name: Test Auth Service
    runs-on: ubuntu-latest
    
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: authdb
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: backend/auth-service/package-lock.json

    - name: Install dependencies
      working-directory: backend/auth-service
      run: npm ci

    - name: Run tests
      working-directory: backend/auth-service
      run: npm test
      env:
        DB_HOST: localhost
        DB_USER: root
        DB_PASSWORD: root
        DB_NAME: authdb
        DB_PORT: 3306
        JWT_SECRET: test-secret-key

    - name: Upload coverage reports
      uses: codecov/codecov-action@v3
      with:
        file: backend/auth-service/coverage/lcov.info
        flags: auth-service
        name: auth-service-coverage

  build-auth-service:
    name: Build Auth Service
    runs-on: ubuntu-latest
    needs: test-auth-service
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: backend/auth-service/package-lock.json

    - name: Install dependencies
      working-directory: backend/auth-service
      run: npm ci

    - name: Build Docker image
      working-directory: backend/auth-service
      run: |
        docker build -t auth-service:latest .
        echo "Auth service Docker image built successfully"

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: auth-service-build
        path: backend/auth-service/
        retention-days: 7 